### ISSUE TITLE
Nuxt generate takes >15 minutes

### ISSUE THREAD

**Issue by Ellissquires** [gregives/gregives.co.uk#1]

**Comment by gregives** [comment]
Possible mitigations:
- Move fonts out of assets into static
- Reduce the number of images produced by responsive-loader
- Reduce the size of images before processing
- Find a better way of requiring dynamic images
- Check webpack bundle analyze again

**Comment by gregives** [comment]
The weirdly long build times were due to sqip-loader, which was used to create the blurry previews for lazy-loaded images. I've now changed this to use responsive-loader to generate placeholders.

As well as this, I've reduced the number of progressive images being generated for each image — the new dimensions are 320px, 640px, 1280px and 1920px.

These changes have reduced build time from ~15 minutes to ~3 minutes.
